### ISSUE TITLE
Document how to checkout the real model files

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet-model-gallery#1]
It's confusing that the zip files can't be decompressed directly. Most users may give up using your models if they fail to figure out that they have to [use git lfs](http://www.sitepoint.com/versioning-large-files-with-git-lfs/).

**Comment by antinucleon** [comment]
I just verified there is no problem to decompress the zip. If don't use git lfs, the file can be downloaded from website directly.

**Comment by futurely** [comment]
Without git lfs, `git clone https://github.com/dmlc/mxnet-model-gallery.git` results in 134 bytes Inception-Full.zip and 133 bytes Inception.zip.

**Comment by antinucleon** [comment]
Thanks for letting me know. We didn't find better place to host. I will add
a note about lfs, and suggest to download from github website directly

**Comment by futurely** [comment]
Neither `git lfs pull` nor `git lfs fetch` worked. Opening in the browser was not stable, but direct downloading succeeded after several trials.
```
Error opening media file buffer.
```
```
Get https://github-cloud.s3.amazonaws.com/alambic/media/118405615/0c/09/0c0943c3756109445fc7c2ffad4cd0828be1b6ce30c69bfcecd932a6d3627148?actor_id=0: dial tcp 54.231.80.136:443: i/o timeout
```
```
Error 503 backend read error

backend read error
Guru Mediation:

Details: cache-nrt6122-NRT 1445830125 2044021406

Varnish cache server
```

**Comment by futurely** [comment]
https://github.com/BVLC/caffe/wiki/Model-Zoo
