### ISSUE TITLE
No labels files for VGG models 

### ISSUE THREAD

**Issue by xslittlegrass** [dmlc/mxnet-model-gallery#22]
It seems that there is no synset.txt file for VGG models at http://www.mxnet.io/models/imagenet/vgg/

I'm wondering where can I found the corresponding labels?

**Comment by tornadomeet** [comment]
it's in the parent folder, http://www.mxnet.io/models/imagenet/

**Comment by xslittlegrass** [comment]
@tornadomeet OK, thanks. Does that mean all the models share the same synset.txt?

**Comment by tornadomeet** [comment]
yes, it is until now.

**Comment by xslittlegrass** [comment]
Thanks!
