### ISSUE TITLE
Alternative ways to access model zip file

### ISSUE THREAD

**Issue by arcadiaphy** [dmlc/mxnet-model-gallery#6]
I want to download the new inception-v3 file, but find the lfs data quota is exceeded. Is there any alternative way to access the model zip file?

Here is what I've got after running lfs pull:
```
(0 of 3 files) 0 B / 244.38 MB
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
```

**Comment by mli** [comment]
thanks for letting us know. now all models are hosted on amazon s3, please have a check

**Comment by arcadiaphy** [comment]
Thanks. Works really fine.
