### ISSUE TITLE
Cannot get the model over git LFS

### ISSUE THREAD

**Issue by ProgramCaiCai** [dmlc/mxnet-model-gallery#8]
This repository is over its data quota. Purchase more data packs to restore access.

**Comment by adihayat** [comment]
same here :+1: 

eadihay@elxgbqn0ky1:~/mxnet/mxnet-model-gallery/imagenet-21k-inception$ git lfs fetch
Fetching master
Git LFS: (0 of 1 files) 0 B / 119.34 MB                                                                                                                                                                     
This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/
Warning: errors occurred

**Comment by zxytim** [comment]
see https://www.kaggle.com/c/yelp-restaurant-photo-classification/forums/t/18199/external-data-mxnet-pretrained-model/103425, said Bing Xu:

"I am sorry recently I formatted my system and I have no backup. I am not sure when the quota will be reset. Once I find my backup I will seek a new place to host it."

**Comment by luxiangju** [comment]
when i download Inception-Full.zip directly from  github, the file is empty...when i open it from github, it says:version https://git-lfs.github.com/spec/v1
oid sha256:ced70db50da509ac59e9ddfb48cf4931449f56b70141d2b69d9b62e411ac737d
size 125137106
how could i download it?

**Comment by shackenberg** [comment]
Hi, I tried yesterday (1st of February) to pull the data, but the repo is still over quota. Did anyone manages to download file?

**Comment by ridambatra** [comment]
i tried today to pull the model , but no success! i need to download it

**Comment by futurely** [comment]
@antinucleon , @mli , @erogol  Does anyone have a copy of the 21k-class Inception model? Would you please share your model files with some free cloud storage services such as [Baidu Cloud](http://pan.baidu.com/). Thanks a lot!

**Comment by 5urprise** [comment]
Here is the Inception21k-model as dropbox link:
[https://www.dropbox.com/s/es1xn9404p8isia/Inception21k-Full.zip?dl=1](https://www.dropbox.com/s/es1xn9404p8isia/Inception21k-Full.zip?dl=1), the `Readme.md` is included. 
If there are problems with the file, just say.

**Comment by mli** [comment]
@5urprise many thanks for the link! i moved all models into http://data.dmlc.ml/mxnet/models and also updated https://github.com/dmlc/mxnet-model-gallery
